version: "3.7"

networks:
  tootdb:
    name: tootdb
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24

services:
  tootdb-a: &tootdb
    build: ..
    environment:
    - tootDB_LOG_LEVEL
    volumes:
    - ./tootdb-a/tootdb.yaml:/etc/tootdb.yaml
    - ./tootdb-a/data:/var/lib/tootdb
    networks:
      tootdb:
        ipv4_address: 172.20.0.101
    ports:
    - 9601:9605

  tootdb-b:
    <<: *tootdb
    volumes:
    - ./tootdb-b/tootdb.yaml:/etc/tootdb.yaml
    - ./tootdb-b/data:/var/lib/tootdb
    networks:
      tootdb:
        ipv4_address: 172.20.0.102
    ports:
    - 9602:9605

  tootdb-c:
    <<: *tootdb
    volumes:
    - ./tootdb-c/tootdb.yaml:/etc/tootdb.yaml
    - ./tootdb-c/data:/var/lib/tootdb
    networks:
      tootdb:
        ipv4_address: 172.20.0.103
    ports:
    - 9603:9605

  tootdb-d:
    <<: *tootdb
    volumes:
    - ./tootdb-d/tootdb.yaml:/etc/tootdb.yaml
    - ./tootdb-d/data:/var/lib/tootdb
    networks:
      tootdb:
        ipv4_address: 172.20.0.104
    ports:
    - 9604:9605

  tootdb-e:
    <<: *tootdb
    volumes:
    - ./tootdb-e/tootdb.yaml:/etc/tootdb.yaml
    - ./tootdb-e/data:/var/lib/tootdb
    networks:
      tootdb:
        ipv4_address: 172.20.0.105
    ports:
    - 9605:9605
